apiVersion: v1
data:
  POSTGRES_DB: webcrawler
  POSTGRES_USER: TONI
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-24T12:40:36Z"
  name: db-config
  namespace: default
  resourceVersion: "29261"
  uid: dd60a3cb-a1b0-4324-b463-0762d1e0d8b3
